name: Deploy Docker Image

on:
  schedule:
    - cron: '0 23 * * *' # daily at 23:00

jobs:

  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          CREATE_PATCH_VERSION_TAG: true
          COMMIT_MESSAGE: "Daily build incorporating updates from kalilinux/kali-rolling"

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Deploy the Docker image to GitHub Package Registry (Wordlists)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali-artis3n/kali
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        buildoptions: "--target wordlists"
        tags: "latest,daily"
    
    - name: Deploy the Docker image to GitHub Package Registry (Base)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali-artis3n/kali
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        buildoptions: "--target base"
        tags: "latest-no-wordlists,daily-no-wordlists"

    - name: Deploy the Docker image to Docker Hub (Wordlists)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        buildoptions: "--target wordlists"
        tags: "latest,daily"
    
    - name: Deploy the Docker image to Docker Hub (Base)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        buildoptions: "--target base"
        tags: "latest-no-wordlists,daily-no-wordlists"
